### ISSUE TITLE
i want  to Test Device Bacnet Simulator 

### ISSUE THREAD

**Issue by niteshaatapaha** [RAKWireless/lorawan-bacnet-bridge#1]
Hello I want to Test Bacnet Virtual device YABE Explorer but its an error [BACNET] Error defining BACnet interface at 172.16.16.75:47808 Please Help me read this device property

**Comment by xoseperez** [comment]
Hi
This error is probably due to the IP being wrong or the port used. The IP is supposed to be the IP of the local machine. The server tries to guess it but if it fails you can set it manually like this in you config file:

```
bacnet:
  ip: 192.168.1.132
  mask: 24
  port: 47808
```
